### ISSUE TITLE
Quicksight Analyses creation failed in step function

### ISSUE THREAD

**Issue by snjkumar23** [aws-solutions/improving-forecast-accuracy-with-machine-learning#30]
**Describe the bug**
Quicksight Analyses creation failed in step function

**To Reproduce**
Upload sample csv file, step function will trigger but fails at quicksight analyses creation phase.

**Expected behavior**
Should have created quicksight dashboard

**Please complete the following information about the solution:**
- [ ] Version: Latest

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0123) Improving Forecast Accuracy with Machine Learning v1.3.0[...]".

- [ us-east-1] Region: us-east-1
- [ No] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ Yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [Yes ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).\
<img width="1440" alt="Screenshot 2023-09-01 at 4 11 32 PM" src="https://github.com/aws-solutions/improving-forecast-accuracy-with-machine-learning/assets/129384708/cdb65529-d28d-41de-ad86-7b6cacf48df0">
<img width="1440" alt="Screenshot 2023-09-01 at 4 11 07 PM" src="https://github.com/aws-solutions/improving-forecast-accuracy-with-machine-learning/assets/129384708/b9b4ccaf-e197-4383-ae35-d015c13b7386">

**Additional context**

**Comment by saccomi** [comment]
Hi @snjkumar23. Thank you for reporting this error. I am currently investigating the template issue with QuickSight analysis and will update you when I can push out a fix.

**Comment by snjkumar23** [comment]
Hi @saccomi - Any update on this.

**Comment by saccomi** [comment]
Hi @snjkumar23. v1.5.5 has been published, but it appears the issue still remains for the QuickSight Lambda step. We plan to do a hotfix patch, but to get you going you can update the Lambda function code to the following and then re-upload your data to run through the Step Function(s) again.

![image](https://github.com/aws-solutions/improving-forecast-accuracy-with-machine-learning/assets/137312802/a3a3e9be-fe00-4c0f-8177-c57f8c0e1ec6)

**This is the added line:**
source_template = "arn:aws:quicksight:us-east-1:898061675696:template/solutions_improving-forecast-accuracy-with-machine-learning_v1_5_5"

Make sure you press the "Deploy" button so that it saves. This should work for you for every model you use on this deployment. Thanks.

**Comment by saccomi** [comment]
We pushed another quick update and this is resolved in v1.5.6., so please update at your earliest convenience. I'm going to go ahead and close this issue.
